
# Main configuration file for motion retargeting training

defaults:
  - train: default
  - model: default
  - _self_

# Runtime settings
device: cuda
verbose: false
visualize_data_first: false

# TRAINING / RETARGETING
source: character2 
target: Rub

resume_from: Null

seed: 123132

logger:
  use_wandb: False
  wandb_project: "deep-skeletal-retargetting"
  wandb_run_name: "humanoid-retarget"

# Hydra settings
hydra:
  run:
    dir: outputs/${source}_to_${target}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false 