seed: 42

experiment:
  directory: "cartpole_test"
  experiment_name: ""

models:
  actor:
    hidden_layers: [512, 256]
    activation: relu
    noise_std_type: fixed
    init_noise_std: 0.055
    weight_init:
      type: uniform
      trunk:
        enabled: false
        zero_bias: true
      output:
        enabled: false
        gain: 0.01
        zero_bias: true

  critic:
    hidden_layers: [512, 256]
    activation: relu
    weight_init:
      type: uniform
      trunk:
        enabled: false
        gain: 1.0
        zero_bias: true
      output:
        enabled: false
        zero_bias: true

storage:
  # None

agent:
  class_type: PPO

  num_mini_batches: 4
  num_learning_epochs: 4
  learning_rate: 1e-3

  clip_param: 0.2
  value_loss_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 1.0
  use_clipped_value_loss: True
  value_loss_clip_param: 0.2

  desired_kl: 0.01
  adaptive_kl: False
  
  gae_lambda: 0.95
  discount: 0.99
  normalize_advantage_per_batch: True


runner:
  timesteps: 2000000
  num_transitions_per_env: 32

  log_interval: 1
  checkpoint_interval: 100  # iterations between saves