seed: 42

experiment:
  directory: "cartpole_test"
  experiment_name: ""
  write_interval: 100
  checkpoint_interval: 100

models:
  actor:
    hidden_layers: [64, 64]
    activation: elu
    noise_std_type: fixed
    init_noise_std: 0.055
    weight_init:
      type: uniform
      trunk:
        enabled: false
        zero_bias: true
      output:
        enabled: false
        gain: 0.01
        zero_bias: true

  critic:
    hidden_layers: [64, 64]
    activation: elu
    weight_init:
      type: uniform
      trunk:
        enabled: false
        gain: 1.0
        zero_bias: true
      output:
        enabled: false
        zero_bias: true

storage:
  # None

agent:
  class_type: PPO

  num_mini_batches: 8
  num_learning_epochs: 8
  learning_rate: 0.0005

  clip_param: 0.2
  value_loss_coef: 1.0
  entropy_coef: 0.01
  max_grad_norm: 1.0
  use_clipped_value_loss: False
  value_loss_clip_param: 0.2

  desired_kl: 0.01
  adaptive_kl: False
  
  gae_lambda: 0.95
  discount: 0.99
  normalize_advantage_per_mini_batch: True


runner:
  timesteps: 100000
  num_transitions_per_env: 32