seed: 42

experiment:
  directory: "locomotion"
  experiment_name: "walking_standing_still"

logger:
  backend: tensorboard
  write_interval: 1
  checkpoint_interval: 50

description: "Describe your run here."
