seed: 42

experiment:
  directory: "humanoid_ppo_walk"
  experiment_name: ""

logger:
  backend: tensorboard
  write_interval: 1
  checkpoint_interval: 60

models:
  actor:
    hidden_layers: [256, 256]
    activation: elu
    noise_std_type: fixed
    init_noise_std: 0.055
    weight_init:
      type: uniform
      trunk:
        enabled: false
        zero_bias: true
      output:
        enabled: false
        gain: 0.01
        zero_bias: true

  critic:
    hidden_layers: [256, 256]
    activation: elu
    weight_init:
      type: uniform
      trunk:
        enabled: false
        gain: 1.0
        zero_bias: true
      output:
        enabled: false
        zero_bias: true

storage:
  # None

agent:
  class_type: PPO

  num_transitions_per_env: 16

  num_mini_batches: 2
  num_learning_epochs: 6
  learning_rate: 0.00005

  clip_param: 0.2
  value_loss_coef: 2.0
  entropy_coef: 0.0
  max_grad_norm: 0.0
  use_clipped_value_loss: False
  value_loss_clip_param: 0.2

  desired_kl: 0.01
  adaptive_kl: False
  
  gae_lambda: 0.95
  discount: 0.99
  normalize_advantage_per_mini_batch: False


runner:
  timesteps: 200000000
  use_pbar: False
